paths:
  model_output: models/xgb_churn_model.pkl
  optuna_study_output: models/optuna_study.pkl

modeling:
  use_gpu: true
  xgb_params:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    gamma: 0
    reg_alpha: 0
    reg_lambda: 1
