paths:
  raw_data: "data/raw/E Commerce Dataset.xlsx"
  model_output: "models/best_model.pkl"
  optuna_study_output: "models/optuna_study.pkl"
  model_output_full: "models/full_pipeline_model.pkl"
data:
  sheet_name: "E Comm"
  target: "Churn"
  test_size: 0.2
modeling:
  use_gpu: false
  xgb_params:
    n_estimators: 300
    max_depth: 5
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
